name: Publish CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:
    branches:
      - master
      - Dev

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.402

      - name: Install dependencies
        run: dotnet restore .\PrettyXML.VSMac\PrettyXML.VSMac.sln

      - name: Build
        run: msbuild .\PrettyXML.VSMac\PrettyXML.VSMac\PrettyXML.VSMac.csproj /t:rebuild -property:Configuration=Release

      - name: Upload Artifacts
        if: ${{ github.event_name == 'push' && github.base_ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2.2.0
        with:
          path: /Users/runner/work/PrettyXML.VSMac/PrettyXML.VSMac/PrettyXML.VSMac/PrettyXML.VSMac/bin/Release/net48/
