name: .NET Core

on:
  push:
    branches:
      - master
      - Dev
      - 'gh-actions'
        
  pull_request:
    branches:
      - master
      - Dev
      
  workflow_dispatch:
    branches:
      - master
      - Dev
      - 'gh-actions'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
    - uses: actions/checkout@v2.3.3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402  
    
    - name: Set directory
      run: Set-Location ./PrettyXML.VSMac/PrettyXML.VSMac
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
