name: .NET Core

on:
  push:
    branches:
      - master
      - Dev
      - 'gh-actions'
        
  pull_request:
    branches:
      - master
      - Dev
      
  workflow_dispatch:
    branches:
      - master
      - Dev
      - 'gh-actions'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
    - uses: actions/checkout@v2.3.3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402  

    - name: Install Mono
      run : |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew install mono
      
    - name: Set directory
      run: sl .\PrettyXML.VSMac\PrettyXML.VSMac\
        
    - name: Install dependencies
      run: dotnet restore .\PrettyXML.VSMac\PrettyXML.VSMac.sln
      
    - name: Build
      run: dotnet build .\PrettyXML.VSMac\PrettyXML.VSMac\PrettyXML.VSMac.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test .\PrettyXML.VSMac\PrettyXML.VSMac\PrettyXML.VSMac.csproj --no-restore --verbosity normal
